### ISSUE TITLE
Lag forsiden med riktig design

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1]
- Designet skal være mest mulig likt designet på https://www.kvalitetsregistre.no/
- Fire firkantede knapper, som skal inneholde det som er runde knapper på https://skde.org/ i dag.
- Implementeres i [nextjs](https://nextjs.org/)?

Design:
![SKDE portal](https://user-images.githubusercontent.com/136346/116415144-6cfc2c00-a839-11eb-9f12-2c2c35aaaf19.jpg)

**Comment by LarsJK** [comment]
Hvordan ønsker dere at vi skriver css? Er glad i å bruke [tailwind](https://tailwindcss.com) selv, men skriver gjerne plain css eller css modules om dere foretrekker det.

@yte0 @arnfinn

**Comment by yte0** [comment]
har ikke brukt tailwind og er mest komfortabel med plain css/css module.

**Comment by LarsJK** [comment]
@arnfinn Kunne dere sendt over bilder og logo?

**Comment by gabriofr** [comment]
@arnfinn : Har dere photoshop fil, fonter, design-manual? Eller skal jeg prøve trekke det ut fra https://www.kvalitetsregistre.no/

**Comment by arnfinn** [comment]
@gabriofr: Jeg skal prøve å få tak i designeren og spørre henne om flere filer.

**Comment by arnfinn** [comment]
@gabriofr  Jeg fikk en `pdf`, i tillegg til en `.sketch`-fil på ~300 mb. Er dette noe du kan bruke, eller vil det væte like greit å ta utgangspunkt i https://www.kvalitetsregistre.no/? Er det eventuelt noe annet jeg kunne spurt om å få?

[SKDE forside.pdf](https://github.com/mong/mongts/files/6420948/SKDE.forside.pdf)

**Comment by gabriofr** [comment]
Jeg bruker bare kvalitetsregistre.no, er godt i gang med det nå :)
