### ISSUE TITLE
SSL uten www

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#121]
Nok en feil, fra annen bruker enn meg.

![image](https://user-images.githubusercontent.com/136346/142399641-8980c7dd-8833-42bf-8008-cd63b628733c.jpeg)

**Comment by areedv** [comment]
Har du litt mer info @arnfinn ?

**Comment by arnfinn** [comment]
Bruker skrev inn `skde.no` og trykket `Enter`. Windows og Chrome vil jeg tro. Det står `www` på bildet, men det er fordi bruker begynte å skrive det i stedet.

Jeg får feil hvis jeg kopierer inn `https://skde.no/` i nettleser.

**Comment by areedv** [comment]
Ja, og det er en kjent sak fra før, altså at skde.no uten www. foran, gir dette utslaget. Jeg husker ikke detaljene, men det gjør nok @rogereriksen Tror det har noe å gjøre med rutingen hos HNIKT av skde.no

**Comment by rogereriksen** [comment]
www.skde.no peker til d3joyj1rwssnpk.cloudfront.net [143.204.47.49]
skde.no peker til adressen 52.18.59.220

Sistnevnte kan ikke ha korrekt sertifikat installert.
________________________________

**Comment by rogereriksen** [comment]
Jeg ser at behov for sertifikat på 52.18.59.220 bare kreves når brukeren skriver "https://skde.no" i nettleseren - ikke når brukeren skriver "skde.no". I sistnevnte tilfelle rutes brukeren direkte til "www.skde.no"

Roger
________________________________

**Comment by arnfinn** [comment]
@rogereriksen Enkelte brukere som skriver `skde.no` blir ikke rutet videre til `www.skde.no`. Jeg har ikke funnet ut hvorfor dette av og til skjer.

**Comment by areedv** [comment]
Jeg gjør et forsøk på å etablere en alternativ tilnærming der målet er å benytte eksisterende sertifikat (skde.no) i kombinasjon med en statisk ip som kan benyttes i HNIKT sin DNS (ved oppslag mot skde.no). Vet ikke hvor det fører hen, men er i alle falle et første forsøk på å komme rundt problemet.

**Comment by areedv** [comment]
Da har jeg satt opp en ny revers proxy med noe tjafs i forkant som kan møte forespørsler (på port 80 og 443) med vårt innebygde aws-sertifikat og med en statisk ip-adresse som da kan settes opp i HNIKT sin DNS. Det er ikke tydelig for meg hvordan oppsettet kan testes og jeg er derfor usikker på om det vil fungere i praksis... Vi få ta opp tråden til uka, flere hoder tenker bedre enn ett

**Comment by areedv** [comment]
> @rogereriksen Enkelte brukere som skriver `skde.no` blir ikke rutet videre til `www.skde.no`. Jeg har ikke funnet ut hvorfor dette av og til skjer.

Jeg vet hvorfor. Eksisterende revers proxy (52.18.59.220) klarer fint å omdirigere forespørsler til www.skde.no når disse kommer i klartekst (på port 80, altså http). Men, den har ingen tilgang til vår aws-sertifikat og har da ingen mulighet til å pakke ut (krypterte) forespørsler (på port 443, altså https).

I den grad dette virker "av og til" så må det komme av at ulike nettlesere eller deres innstillinger varierer på protokollen som velges for en forespørsel, altså http eller https når en bruker ber om en site, eksempelvis "skde.no".

**Comment by areedv** [comment]
Det finnes nå et forslag til løsning på problemet. Løsningen krever, i tillegg til ny infrastruktur som allerede er satt opp på AWS, at HNIKT endrer DNS oppslaget til skde.no. Med mindre vi finner feil eller utilstrekkeligheter ved eget oppsett så vil @rogereriksen sørge for at endringen i DNS skjer førstkommende fredag, 26. november 2021. Så vidt jeg forstår kan en slik endring i DNS ta noe tid før den når ut til alle DNS-registre rundtomkring. Jeg lukker derfor saken nå, så får vi heller gjenåpne om vi kommer over skjær i sjøen.
