### ISSUE TITLE
Helseatlas-siden klikker når man bytter atlas i meny

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1221]
## Reproduksjon

Gå inn på Helseatlas Kronikere. Åpne meny. Velg Helseatlas Kvalitet.

## Feilmelding

```
Unhandled Runtime Error
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```

eller

```
Unhandled Runtime Error
Error: Rendered more hooks than during the previous render.
```

![image](https://github.com/mong/mongts/assets/136346/fde51ffe-ae48-4144-8e73-abe42a336c81)

**Comment by Stein-Kato** [comment]
Problemet kommer av at `TocDataToList` er rekursiv og har en Hook. Når man velger et annet atlas endres antall ganger den kaller seg selv avhengig av antall overskrifter og seksjoner under hver overskrift.

**Comment by jo-inge-arnes** [comment]
TocDataToList brukes nå som en komponent som settes inn som en tag (<TocDataToList ... osv />) i stedet for et funksjonskall.
