### ISSUE TITLE
ved fane "datakvalitet" når man velger "Alle indikatorer" får man ikke opp alle registrene i listen under

### ISSUE THREAD

**Issue by larstun** [mong/mongts#1383]
![image](https://github.com/mong/mongts/assets/143407861/3dd15a56-4257-4e3a-8f90-d7e656a09822)

Forsøkte å finne Ryggregisteret under alle indikatorer på datakvalitet for å finne dekningsgraden, men denne indikatoren dukker ikke opp på denne listen. Men finner indikatoren for dekningsgrad når man trykker inn på registeret.

Det er nok gjeldende for flere registre at dekningsgraden ikke dukker opp under "Alle indikatorer", bare om hvorfor det er sånn at noen dukker opp og andre ikke dukker opp under "alle indikatorer"

**Comment by arnfinn** [comment]
@larstun Det er sannsynligvis fordi Ryggregisteret ikke har dekningsgrad-tall fra 2022. Det er kun data for 2022 som vises her. Når du går inn på et register vises data fra siste år det finnes data.
