### ISSUE TITLE
Investigate geojson

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#1636]
Investigate what the "kart" field in a result box is really doing, and what the geojson files are used for. Is it only one, that everyone uses? Is this the default if nothing is set?

**Comment by arnfinn** [comment]
De fleste resultatbokser bruker samme kart-grunnlag, men i noen få tilfeller må enkelte opptaksområder slås sammen fordi tallene blir for små hver for seg.

Se _Indre Oslo_ her: https://www.skde.no/helseatlas/v2/hjarteinfarkt/?bohf=Indre+Oslo. For tre av resultatboksene er Lovisenberg og Diakonhjemmet slått sammen til Indre Oslo. Da må det brukes et annet kart-grunnlag (geojson-fil).
