### ISSUE TITLE
utforme og teste figma design over til kode

### ISSUE THREAD

**Issue by larstun** [mong/mongts#1642]
- Teste export av komponent fra figma til kode

**Comment by larstun** [comment]
Lagt ut filterbokser i figma til developer, kan sjekke opp om exporten som en komponent med netrekk?

![Image](https://github.com/mong/mongts/assets/143407861/e262cdd8-1602-4b2d-a88d-4c2b03ab3521)

**Comment by jo-inge-arnes** [comment]
Har ikke fått eksporten av nedtrekk til å funke. Har brukt et par forskjellige plugins (Anima, Builder.io, Figma to Code), og også forskjellige innstillinger for de ulike. Anima ser ut til å funke best, men heller ikke der kommer bildene med på nedtrekket.

Tror nok vi må satse på å skrive mye av koden selv, men vi kan hente en del info om styling fra figma allikevel.
