### ISSUE TITLE
Bedre logikk på om indikatorer skal vises eller ikke hvis dekningsgrad mangler helt

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1650]
I dag vises indikatorer hvis dekningsgrad mangler.

Usikker på hvordan vi kan løse dette.

**Comment by larstun** [comment]
Mener du når det vises slik? 


![Image](https://github.com/mong/mongts/assets/143407861/fa5f2449-a552-421f-a338-36e944f8262c)

**Comment by larstun** [comment]
Tvinge registrene til å ha dekningsgrad på indikatorene
