### ISSUE TITLE
Teller og nevner i søylediagram.

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1653]
Gjerne skrevet på, men går også med tooltip. Vil gjerne ha nevner og teller inn i figur som lastes ned.

Sluttbruker ønsker å få teller og nevner i søylediagrammet, og når de skal kopiere/skrive ut figuren skal teller og nevner følge med søylediagrammet.

![Image](https://github.com/mong/mongts/assets/143407861/d2ff6fdf-3866-466e-b963-a989dc5af764)

**Comment by larstun** [comment]
Egen knapp for vis teller/nevner i barcharten?
