### ISSUE TITLE
Workshop 1 for veien videre med helseatlas

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1654]
Arrangere workshop med analyseseksjonen for å avklare og diskutere ønsker og behov for visning av resultater fra helseatlastjenesten.

- Opptaksområde-profil?
- Løpende oppdateringer?
- Videreutvikling av CMS?
- Revurderingsprosjektet?

**Comment by larstun** [comment]
Må vurdere 2 ulike workshops for dette:

- [ ] Behov/design workshop med Helseatlas-folkene (analyse/Førde folkene?) 
- [ ] Teknisk workshop basert på tegning/utkast fra behov/design workshop

**Comment by larstun** [comment]
Gjennomført en workshop med analyseseksjonen 22.02.24, tilbakemeldinger er ført inn i figma-filen. Trengs mer avklaring med analyseseksjonen samt flere workshops
