### ISSUE TITLE
Bytte fra jest til (f.eks.) vitest

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1698]
Jeg sliter med å oppdatere til siste versjon av noen markdown-pakker (#1462). [Andre](https://www.github.com/orgs/remarkjs/discussions/1247) har opplevd det samme. I https://www.github.com/orgs/remarkjs/discussions/1247 forelås det å gå for et mer moderne test-rammeverk, nemlig [vitest](https://vitest.dev/).

@jo-inge-arnes høres  dette fornuftig ut? Jeg kan prøve å konvertere. I følge [vitest](https://vitest.dev/guide/migration.html) skal det være enkelt.

**Comment by jo-inge-arnes** [comment]
Sikkert fornuftig. Har ikke satt meg inn i Vitest. Vet bare at Vite brukes mye i forbindelse med Vue.

**Comment by arnfinn** [comment]
Følgende tester hos qmongjs fungerer ikke med vitest og må eventuelt over til cypress:

```
src/components/RegisterPage/unitnamelist/__tests__/unitnamelist.test.tsx
src/components/IndicatorTable/indicatorrow/__test__/indicatorrow.test.tsx
src/components/RegisterPage/header/__test__/header.test.tsx
src/components/IndicatorTable/__test__/indicatortable.test.tsx
```

**Comment by jo-inge-arnes** [comment]
Kanskje de kan skrives om eller byttes ut med nye tester. Vet du hva som gjør at de ikke fungerer? Er det på grunn av noe mocking, spesielle biblioteker? Eventuelt, kanskje de ikke er så relevante lenger...

**Comment by jo-inge-arnes** [comment]
Er det et alternativ å kommentere ut testene for å gjort overgangen til vitest, og deretter fikse dem en og en?

**Comment by arnfinn** [comment]
Satser på å gjøre de om til Cypress-tester (se issue #1761 og PR #1726)

**Comment by arnfinn** [comment]
> Vet du hva som gjør at de ikke fungerer? Er det på grunn av noe mocking, spesielle biblioteker? Eventuelt, kanskje de ikke er så relevante lenger...

Feiler med
```
  stderr | src/components/IndicatorTable/indicatorrow/__test__/indicatorrow.test.tsx > renders with low achievement level and not complete year
  Error: Uncaught [Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted]
```

Jeg sletter testene og så kan vi prøve å få de (og andre) inn igjen senere.
