### ISSUE TITLE
Aktivere skde.no/admin

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#17]
Fungerer ikke out-of-the-box når siden hostes på AWS:

![image](https://user-images.githubusercontent.com/136346/121534790-d73fe900-ca01-11eb-8176-34857f3e7576.png)

Det fungerer hvis siden hostes på netlify.

https://www.pulumi.com/blog/deploying-netlify-cms-on-aws/

**Comment by LarsJK** [comment]
@arnfinn Fikset på qa. Tester du at du får redigert artikkler?

Den står foreløpig på min OAuth app men dere kan gå å lage en egen her https://github.com/organizations/mong/settings/applications og sette inn riktig client id og secret i env variablene på beanstalk

**Comment by arnfinn** [comment]
Jeg godtar din OAuth og så ender jeg opp her:

![image](https://user-images.githubusercontent.com/136346/122885878-c23b5200-d33f-11eb-87ca-6af2024c7eb8.png)

Uten innhold.

**Comment by LarsJK** [comment]
@arnfinn hvilken nettleser? Kan du teste med en annen? Åpner det vinduet seg i en popup?

**Comment by yte0** [comment]
@LarsJK  får det samme på firefox

**Comment by yte0** [comment]
ja, siden åpner seg i et popup vindu.

**Comment by LarsJK** [comment]
Servere noen feilmeldinger i consollen? Jeg skal teste med flere maskiner/nettlesere her å forsøke å gjennskape.
Den virker hos meg i Safari og Firefox, og for Kristian i chrome. Kristian har ikke tilgang men ser ut som at Flowen virker

**Comment by yte0** [comment]
får dette i consolen til popup vinudet

![Skjermbilde](https://user-images.githubusercontent.com/54272616/122909110-24528200-d355-11eb-84be-db119d8bc511.PNG)

**Comment by LarsJK** [comment]
Går dere på https://qa.skde.org/admin/index.html når dere skal logge inn?

**Comment by arnfinn** [comment]
https://qa.skde.org/admin/index.html fungerte fint!

**Comment by LarsJK** [comment]
Bra. Dere må opprette en integrasjon på https://github.com/organizations/mong/settings/applications, og sette id og secret i beanstalk.
Det er kanskje bare nødvendig med en prod integrasjon.

**Comment by arnfinn** [comment]
I orden nå.
