### ISSUE TITLE
Sykehusviser: data vises ikke

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1846]
Lungekreft 2023:

https://www.skde.no/kvalitetsregistre/lungekreft/opptaksomraade/?year=2023
![image](https://github.com/mong/mongts/assets/136346/9dcfd9d4-a453-4068-b0cc-875464722048)

Nasjonale data dukker opp når enhet velges:

https://www.skde.no/kvalitetsregistre/lungekreft/opptaksomraade/?year=2023&selected_treatment_units=Volda
![image](https://github.com/mong/mongts/assets/136346/bea5fe88-5f3d-4da7-a80e-b20df74e3855)

**Comment by larstun** [comment]
Data viser ikke når du velger 2023 og trykker på valgt fagområde, f.eks Kreft

![image](https://github.com/mong/mongts/assets/143407861/d818493e-38a1-4646-b53e-96a1b1e44f1d)

til forskjell for fagområde - Luftveier
![image](https://github.com/mong/mongts/assets/143407861/89e1e61f-910e-42a1-9e1d-c16eb1edcfa0)

**Comment by arnfinn** [comment]
@Stein-Kato Ville du grave litt i denne? Eventuelt sammen med @Uglemat?

**Comment by Stein-Kato** [comment]
> @Stein-Kato Ville du grave litt i denne? Eventuelt sammen med @Uglemat?

Tar saken

**Comment by arnfinn** [comment]
Mer permanent løsning hvis vi løser denne: https://github.com/mong/imongr/issues/283

**Comment by larstun** [comment]
Samme problem for Psykisk helse og rus, hudsykdommer og nyre fagområde @arnfinn
