### ISSUE TITLE
Få dato inn i «Data er ikke komplett. Siste komplette år er 2022»

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#1847]
Burde stå «Data er ikke komplett. Data er komplett før 30. juni 2023» eller lignende. Hente data fra det som er innrapportert i feltet "Merk alle indikatorer som foreløpig etter:" i imongr.

**Comment by arnfinn** [comment]
@larstun noen forslag til OK tekst her?

**Comment by larstun** [comment]
- Data for [ÅR] er komplett til og med [DATO].  
- Data for [ÅR] er fullkommen til og med [DATO].
- Komplette data for [ÅR] fram til [DATO]. 
- Data som vises for [ÅR] er komplett fram til [DATO].

**Comment by arnfinn** [comment]
@Stein-Kato Vil du koze deg med denne?

**Comment by Stein-Kato** [comment]
> @Stein-Kato Vil du koze deg med denne?

Tar den

**Comment by arnfinn** [comment]
Forslag fra Kreftregisteret:
> «Data er komplett til og med 30 juni 2023. Siste komplette årgang er 2022" og at denne ikke står verken i rødt eller i fet skrift

**Comment by larstun** [comment]
Årgang? Høres ut som de har drukket vin... "Data er komplett til og med 30. juni 2023. Siste komplette årstall er 2022" og er enig med å fjerne rød og fet skrift

**Comment by Stein-Kato** [comment]
@arnfinn Ser dette greit ut? 
![image](https://github.com/mong/mongts/assets/64078729/a3faa13e-2df1-4a81-a294-60bb1a6dede9)

**Comment by arnfinn** [comment]
@Stein-Kato Bytte til "... Siste komplette år ..." og sette fargen til svart(-ish).

**Comment by Stein-Kato** [comment]
> @Stein-Kato Bytte til "... Siste komplette år ..." og sette fargen til svart(-ish).

Skal vi fikse på den andre teksten i samme slengen?

**Comment by arnfinn** [comment]
> > @Stein-Kato Bytte til "... Siste komplette år ..." og sette fargen til svart(-ish).
> 
> Skal vi fikse på den andre teksten i samme slengen?

KJør på!
