### ISSUE TITLE
Flytte strapi-cms-app inn i egen branch

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2024]
Slik at det blir mulig å utvikle CMS uavhengig av helseatlas-sidene.

I dag leser helseatlas-sidene fra strapi-innhold, som betyr at dagens branch ikke kan merges inn i main.

**Comment by jo-inge-arnes** [comment]
[] 2024-flytte-strapi-cms-app-inn-i-egen-branch

**Comment by jo-inge-arnes** [comment]
- [ ] Opprette ny Strapi-branch og flytte kode

**Comment by jo-inge-arnes** [comment]
- [ ] https://github.com/mong/mongts/issues/2050
