### ISSUE TITLE
Utrede enhetlig theming/styling av komponentene (mui)

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2036]

**Comment by larstun** [comment]
Ligger profilprogram/designmal i Figma: https://www.figma.com/file/aJQNabiSOPSiVPwUoLcaYZ/interaktive-nettsider?type=design&node-id=1894%3A11081&mode=design&t=rVa0wYwvOcO065UZ-1 

![Image](https://github.com/mong/mongts/assets/143407861/7d1d9014-4f20-4601-b8c8-c49d193a368c)



![Image](https://github.com/mong/mongts/assets/143407861/76906f6c-9783-4c3c-973c-667551700f0b)



![Image](https://github.com/mong/mongts/assets/143407861/517e8293-4871-4aa9-8ff8-90a6d1951608)



[Profilmanual.txt](https://github.com/mong/mongts/files/14903258/Profilmanual.txt)

**Comment by larstun** [comment]
Følger opp med #2276
