### ISSUE TITLE
Får ikke bygget etter strapi-inkludering

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2077]
Jeg sliter med å få bygd mongts etter at strapi kom inn (#2071).

> strapi:build: Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
strapi:build: 
strapi:build: $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
strapi:build: ERROR: command finished with error: command (/home/arnfinn/repo/mong/mongts/apps/strapi) /tmp/xfs-66f66742/yarn run build exited (1)
strapi#build: command (/home/arnfinn/repo/mong/mongts/apps/strapi) /tmp/xfs-66f66742/yarn run build exited (1)
> 
> Tasks:    0 successful, 3 total
> Cached:    0 cached, 3 total
>   Time:    761ms 
> Failed:    strapi#build
> 
>  ERROR  run failed: command  exited (1)

Ser jo ut til å fungere på github, så usikker på hva jeg har gjort galt her. Noen ideer @jo-inge-arnes?

**Comment by jo-inge-arnes** [comment]
Mystisk. Skal se på det i morgen.
