### ISSUE TITLE
Havner i bunnen ved åpning av resultatboks

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2127]
På mobil (iPhone) havner man helt nederst på siden når man åpner en resultatboks. Gjelder Chrome. Safari er ok.

![scroll_bug](https://github.com/mong/mongts/assets/136346/d1d77bfd-0990-4b2e-b455-64724db74aa7)

**Comment by larstun** [comment]
"mirakuløst" løst

**Comment by arnfinn** [comment]
Fikk den tilbake nå...

**Comment by Stein-Kato** [comment]
@arnfinn Kan du sjekke om dette fortsatt er et problem?

**Comment by arnfinn** [comment]
Ja, fremdeles et problem...

**Comment by Stein-Kato** [comment]
@arnfinn Sjekk igjen

**Comment by larstun** [comment]
Løst
