### ISSUE TITLE
Ny figur - Oppdatering Kvalitetsbarometer fra Kvalitetsatlaset

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2134]
Følgende figur fra [kvalitetsatlaset](https://www.skde.no/helseatlas/v2/kvalitet/) ønskes på skde.no med sykehus istedenfor opptaksområder. 

Filtermeny skal kunne brukes for å filtrere ut et utvalg av sykehus og indikatorer. 

![image](https://github.com/mong/mongts/assets/64078729/66f2148a-28d3-434a-bff4-7fbfdaef8d29)

**Comment by larstun** [comment]
@larstun - Innkaller eva og philip til et møte om kvalitetsregisteratlasfigur

**Comment by larstun** [comment]
Fra møte med eva og philip, innkommet ønske fra eksterne om en oppdatering av kvalitetsbarometeret. 
Angitt at gruppen kan muligens løse dette med å gjenbruke de 24 indikatorene som er satt og bytte ut opptaksområde med sykehus/hf/rhf.
Ser på dette til neste sprint.

**Comment by larstun** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LET300~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LET300~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Indikatornr | Indikatornavn | Indikatortype
-- | -- | --
1 | 5-års   relativ overlevelse etter operasjon | colon_relsurv_fra_opr
2 | Andel behandlet med   trombolyse | hjerneslag_beh_tromb
3 | Andel operert med   brystbevarende kirurgi når svulsten er 0-30 mm. | breast_bct_invasiv_0_30mm
4 | Andel i stadium 1   operert med thorakoskopi eller robot | lungekreft_andellobektomithoraskopisk
5 | Andel med HbA1C <   53 mmol/mol | NDV_andel_HbA1C_mindre_eller_lik_53
6 | Andel pasienter   operert med laparoskopi (kikkhullskirurgi) | rectum_laparoskopi
7 | Andel utført   lymfeknutedisseksjon | prostata_utfoert_lymfadenektomi
8 | Sementert stamme ved   bruk av protese | hoftebrudd_stammefiks
9 | Andel fri   reseksjonsmargin pT2 | prostata_fri_reseksjonsmargin
10 | Behandlet innen 14   dagert for forsnevring av halspulsåren | norkar_forsnev_hals_14d
11 | Andel pasienter med   lokalt tilbakefall 5 år etter operasjon | rectum_lokalt_tilbakefall
12 | Andel HbA1C < 75   mmol/mol | NDV_andel_HbA1C_mindre_eller_lik_75
13 | Andel kvinner med   DCIS operert med brystbevarende kirurgi når svulsten er 0-20 mm. | breast_bct_dcis_0_20mm
14 | Ukentlig Kt/V >2,3   (hemodialyse) | nyre_hemodia_ktv
15 | Andel pasienter   operert med laparoskopi (kikkhullskirurgi) | colon_laparoskopi
16 | Koronar angiografi   innen 72 timer ved NSTEMI | hjerteinfarkt_invasivt_nstemi_72t
17 | HbA1c  < 53 mmol/mol | barnediabetes_hba1c_lt_7
18 | Operasjon innen 48   timer | hoftebrudd_ventetid48
19 | Dødelighet 30 dager   etter operasjon | lungekreft_postoperativmortalitet30dager
20 | HbA1c  < 75 mmol/mol | barnediabetes_hba1c_ge_9
21 | Reperfusjonsbehandling   ved STEMI | hjerteinfarkt_reper_stemi
22 | Hjemmedialyse   (dialyse) | nyre_dialyse_hjemme
23 | Trykkmåling ved   innsnevringer i kransårene | noric_trykkmaaling
24 | Blodtrykk <130/80   (transplantasjon) | nyre_transplant_bt



</body>

</html>

**Comment by Stein-Kato** [comment]
@larstun @arnfinn 

![Image](https://github.com/mong/mongts/assets/64078729/0b519160-556e-484d-a989-0768f163179f)

**Comment by larstun** [comment]
Mangler bare nedtrekksmeny for valg av RHF/HF/Sykehus og valg av år :-) 
![image](https://github.com/mong/mongts/assets/143407861/e32bb5ef-9e37-4322-b786-3a0e020ed7ea)
