### ISSUE TITLE
Punkter i linjediagram hvis data vises på bo-område/helseforetak - Helseatlas

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2143]
- [x] #2382 

![Image](https://github.com/mong/mongts/assets/136346/ff0e03c0-d85e-4235-9471-36f6b8875018)

**Comment by larstun** [comment]
https://mui.com/x/react-charts/line-demo/



https://github.com/mong/mongts/assets/143407861/ca5e548a-5ead-4e49-982a-e4a453c48939

**Comment by larstun** [comment]
Fortsette med VISX, bruk linechart

**Comment by Stein-Kato** [comment]
Utgår
