### ISSUE TITLE
Tastaturnavigering sitter fast i behandlingsenheter

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2163]
Hvis jeg har kommet ned på behandlingsenheter kan jeg ikke komme ut av den igjen med <kbd>Shift</kbd>+<kbd>Tab</kbd>. Med <kbd>Tab</kbd> kommer man seg rundt til toppen igjen, men altså ikke motsatt vei.

![tab_bug](https://github.com/mong/mongts/assets/136346/aaa35614-c556-4b37-a4bd-4249b052a0ef)

**Comment by jo-inge-arnes** [comment]
Det er nå mulig å alt-tabbe seg ut fra behandlingsenheter.
