### ISSUE TITLE
Fange opp døde linker i Helseatlas

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#2247]
I Helseatlas legges det ofte inn tekster som inneholder linker til eksterne sider. Det har vist seg at en del av disse linkene ikke lenger er gyldige. For å fange opp slike døde links, bør det lages et script eller lignende for å sjekke at linkene fortsatt fungerer.

For eksempel, man kan kanskje plukke ut linker rett ut fra JSON-filene som benyttes av helseatlas med en regular expression, og deretter sjekke at sidene ikke gir en HTTP-feilmelding når man forsøker å aksessere dem.

**Comment by larstun** [comment]
- [ ] Ferdigstille oppgaven @arnfinn @jo-inge-arnes

**Comment by arnfinn** [comment]
Skal være ok nå. Kunne gjerne sendt epost til utvalgte personer hvis den feiler.
