### ISSUE TITLE
Vis lav DG og lav N i tabell

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2275]

**Comment by larstun** [comment]
Kan vi bruke annet begrep enn "Lav DG" og "Lav N"? Usikker på brukervennligheten ved dette.

Pluss at tooltip-boksen er uleselig med så liten skrift og mye tekst, TLDR. 

![Image](https://github.com/mong/mongts/assets/143407861/c0004ae4-3c5f-4770-99f5-3c22f67d5a72)
