### ISSUE TITLE
Theming/styling (mui) av komponenter

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2276]
Oppfølging til issue #2036 

https://mui.com/material-ui/customization/default-theme/

**Comment by larstun** [comment]
Forslag om å bruke primærfarger samsvarer med HSV kode istedenfor farge RGBA

**Comment by larstun** [comment]
Ferdig design i Figma: https://www.figma.com/file/aJQNabiSOPSiVPwUoLcaYZ/interaktive-nettsider?type=design&node-id=0-1&mode=design

Designmal i Figma: https://www.figma.com/file/aJQNabiSOPSiVPwUoLcaYZ/interaktive-nettsider?type=design&node-id=1390-3603&mode=design

**Comment by Stein-Kato** [comment]
@larstun 

[SKDEtheme.txt](https://github.com/mong/mongts/files/15040117/SKDEtheme.txt)
