### ISSUE TITLE
Lage en BarchartBase-komponent

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2297]

**Comment by larstun** [comment]
https://mui.com/x/react-charts/

**Comment by Stein-Kato** [comment]
@lars Har vi en skisse på hvordan søylediagrammet skal se ut? Mener å huske at det var snakk om å få med teller og nevner på hver søyle.

**Comment by larstun** [comment]
Tror vi må bare gå ut ifra den gamle først
![image](https://github.com/mong/mongts/assets/143407861/a88cb4f9-5d98-408c-b443-dc064c3d044f)
