### ISSUE TITLE
Visning av indikatorer i tabell

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2307]
- Hva skal stå i celler med lav dg eller lav N? 
- Skal vi vise rader der det kun finnes data nasjonalt? 
- Hvordan håndterer vi indikatorer uten oppgitt dekningsgrad? 

![Image](https://github.com/mong/mongts/assets/64078729/b6efa92e-b529-4d01-9647-fa18660c6ca4)

**Comment by larstun** [comment]
Lav DG og Lav N er i mine øyne ikke veldig "folkelig".

Kommer med forslag...
Lav DG/Lav N/Ingen data - N/A (Infotekst - Ikke anvendbare data, se datakvalitet) ?

**Comment by jo-inge-arnes** [comment]
Bør kanskje være noe som er mer forståelig for hvermannsen.
"Lite data" og "Lav dekning"?

**Comment by larstun** [comment]
Jeg har litt tillit til hvermannsen at de kanskje forstår "N/A" ?
Med infoboks når man hovrer over "N/A"

![image](https://github.com/mong/mongts/assets/143407861/69890b9a-6a87-428e-aef4-59e6ec0ea651)
