### ISSUE TITLE
Bug i fotnoter i lang indikatorbeskrivelse

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2314]
Når man klikker på linken til en fotnote i lang indikatorbeskrivelse skal siden skrolle ned til fotnoten. Per nå havner man på toppen av siden i en ny fane. 

![image](https://github.com/mong/mongts/assets/64078729/aae4def5-bb55-4c6b-9d4c-a7281d23f374)

Problemet oppstår fordi `remark-gfm` lager en `href` automatisk med formen `user-content-fn-x` hvor x er et tall. Derfor blir det duplikater av id-er.

**Comment by arnfinn** [comment]
Slå av href på fotnoter

**Comment by arnfinn** [comment]
Konklusjon: fjerne fotnote-link. Trengs ikke.

**Comment by Stein-Kato** [comment]
Konklusjon: fjerne fotnoter fullstendig og legge inn referansene manuelt.
