### ISSUE TITLE
Langt mellomrom på mobilvisning mellom indikatorene

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2318]
https://github.com/mong/mongts/assets/143407861/ba896e3b-2dac-4d0a-879c-914d4b27dbd5

**Comment by arnfinn** [comment]
Som gif:

![test](https://github.com/mong/mongts/assets/136346/4616426d-3871-4322-968a-138f2f330a77)

**Comment by Stein-Kato** [comment]
@larstun Fungerer dette som det skal nå?

**Comment by larstun** [comment]
Løst på min rare mobil med newtable, får ikke store mellomrom mellom indikatorene lengre
