### ISSUE TITLE
Ny farge på valgte HF

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2342]
Blå passer dårlig sammen med lilla.

`rgb(74, 182, 155)`, som er color-picked fra [profilen fra regjeringen](https://www.regjeringen.no/contentassets/575f7de1edeb42fca6a952d3ca5f3260/nasjonalt-profilprogram-endelig-versjon-2022.pdf), vil se sånn ut:

![image](https://github.com/mong/mongts/assets/136346/76c88672-a7b7-4f0c-83d1-fbc9f3919523)

**Comment by arnfinn** [comment]
Må kanskje diskuteres med @Uglemat, @hannesigrun etc.

**Comment by Uglemat** [comment]
Jeg tror kanskje problemet er litt mer grunnleggende enn bare hvilken farge man velger i grafen. Slik som helseatlas-siden er nå, er den på en måte bygd opp med to hovedfarger: blå og lilla. Hvis man da endrer på blå på en plass, tror jeg det er best å endre på blå på alle plassene slik at man fortsatt bare har 2 farger. Hvis man endrer til grønn, som i dette tilfellet, ville det sett omtrent slik ut (da blir knappene og linkene også grønne):

![fargevalg](https://github.com/mong/mongts/assets/593262/0d68e4cd-5a84-436c-bca9-55afc1ecf4f6)

Det ser kanskje fortsatt litt rart ut, men det er kanskje lilla som er rarere en grønn i dette bildet.
