### ISSUE TITLE
Fikse bug i tabell

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2343]
Det må tas høyde for indikatorer som ikke er andel

![Image](https://github.com/mong/mongts/assets/64078729/6da61800-55af-4d5f-b792-26fd5f85aa27)

**Comment by larstun** [comment]
@Stein-Kato ble ikke denne fikset?

**Comment by Stein-Kato** [comment]
> @Stein-Kato ble ikke denne fikset?

Ja, det var ikke en bug, men en feil i den lokale databasen.
