### ISSUE TITLE
Utbedre header for Behandlingskvalitet, forskjell på mobilvisning/desktop

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2371]
![Image](https://github.com/mong/mongts/assets/143407861/f66bface-0634-40c2-9fe1-dd30dee03ea3)

Endring på APP-bar til å fungere på mobil-side vs vanlig visning på desktop

**Comment by larstun** [comment]
Har SKDEtheme riktig font? Den bruker Plus Jakarta Sans men ser ikke lik, mangler vi google fonts?

Behandlingskvalitet
![Image](https://github.com/mong/mongts/assets/143407861/bb0e84c8-a3f8-493f-affd-895f2e71d0d5)

i motsetning til Helse Nord

Helse Nord
![Image](https://github.com/mong/mongts/assets/143407861/7ce3b74a-dd69-46a9-bca1-a6d8b107a636)

https://fonts.google.com/selection/embed

**Comment by larstun** [comment]
@jo-inge-arnes - Her er SKDE-logoer

![Image](https://github.com/mong/mongts/assets/143407861/083c4ced-b037-4c8b-b7d8-ff1530dda358)
![Image](https://github.com/mong/mongts/assets/143407861/47d97229-7ee6-48fa-9a6f-fabafa51ab6c)
![Image](https://github.com/mong/mongts/assets/143407861/a3d0667f-900f-470e-a3b3-18af9cd31021)
![Image](https://github.com/mong/mongts/assets/143407861/c081019d-cf37-437c-8f8f-3b7b6f1e6aba)
![Image](https://github.com/mong/mongts/assets/143407861/5b6aa848-cf3e-424d-acc3-a0756eb228eb)
![Image](https://github.com/mong/mongts/assets/143407861/0270283b-7d2d-4cd1-a48a-28d43c77a585)

**Comment by larstun** [comment]
Nr 1 - er den som brukes på nettsiden



![Image](https://github.com/mong/mongts/assets/143407861/d3edef6a-c0fb-47f5-b8de-a52d20a7ab08)

**Comment by jo-inge-arnes** [comment]
Ok, bra. Vurderer en større omstrukturering av siden. Bedre layout/struktur, men uten å omskrive koden som løser de mer tekniske finurlighetene, da.

**Comment by larstun** [comment]
Dette ser veldig nice ut 🤩🤩 Det ser litt tomt ut på høyre siden i headeren og lurer på om det bør være en "hommage" til kvalitetsregistre.no.... for å ikke komme i tverke med servicemiljøet så kunne vi ha logo pluss en boks "Om kvalitetsregistre" der som linker til www.kvalitetsregistre.no  

![Image](https://github.com/mong/mongts/assets/143407861/35183366-8a77-4f9e-a687-bee49784de6a)
