### ISSUE TITLE
Rute qa.skde.no til www.skde.no

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#239]
Vår qa-adresse har spredd seg til media, så vi må rute qa til www, og lage ny qa-adresse for videre nettsideutvikling.

**Comment by rogereriksen** [comment]
Hvordan oppdaget du det?
Jeg skal sende en endring til HN IKT, men kan vi ikke bare bruke skde.org for test og utvikling?

Med vennlig hilsen
Roger Eriksen
Mobil 909 48 146
________________________________
Fra: Arnfinn Hykkerud Steindal ***@***.***>
Sendt: Tuesday, May 3, 2022 11:43:20 AM
Til: mong/mongts ***@***.***>
Kopi: Roger Eriksen ***@***.***>; Assign ***@***.***>
Emne: Re: [mong/mongts] Rute qa.skde.no til www.skde.no (Issue #239)


Assigned #239<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmong%2Fmongts%2Fissues%2F239&data=05%7C01%7C%7C26f997d56ded4098112408da2ce95c68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637871678026532304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PuAqFmyROguPxZY3oag1N18N99ZofX9OKxVqiHp73c0%3D&reserved=0> to @rogereriksen<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frogereriksen&data=05%7C01%7C%7C26f997d56ded4098112408da2ce95c68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637871678026532304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MEVySz86WS1R%2BNSCNDzyUXqePK0B5TATXxpVRv4CAno%3D&reserved=0>.

**Comment by arnfinn** [comment]
> Hvordan oppdaget du det? 

Vi sendte ut adressen i pressemeldinger om siste atlas...

**Comment by areedv** [comment]
Det må i så fall være å bruke qa.skde.org til test og utvikling. skde.org er i seg selv viktig i vårt oppsett for å gi riktig vei inn til våre skarpe tjenester (PROD). Med vårt oppsett (hybrid) så er oppføringer i DNS (som HNIKT forvalter) primært en ruting videre til skde.org og det tror jeg er viktig å opprettholde slik at vi kan ivareta en den oversikt og kontroll som vi trenger

**Comment by arnfinn** [comment]
Fungerer fremdeles ikke hos meg

**Comment by arnfinn** [comment]
@rogereriksen Fungerer fremdeles ikke hos meg. Sendes fremdeles til test-sidene våre.

**Comment by arnfinn** [comment]
@rogereriksen Har du mulighet til å se på denne en gang til? I [NOU 2023:4](https://www.regjeringen.no/contentassets/337fef958f2148bebd326f0749a1213d/no/pdfs/nou202320230004000dddpdfs.pdf) har de oppgitt https://qa.skde.no/helseatlas/ som helseatlas-siden (fotnote 2 på side 239), så qa-adressen deles fremdeles.

**Comment by rogereriksen** [comment]
@arnfinn - både www.skde.no og qa.skde.no peker til d2wfuc55sijwtn.cloudfront.net.
Test-instansen vår test.skde.no peker til en annen bucket: d2wfuc55sijwtn.cloudfront.net

**Comment by arnfinn** [comment]
@rogereriksen

**Comment by larstun** [comment]
Er denne løst?

**Comment by arnfinn** [comment]
> Er denne løst?

Nei

**Comment by rogereriksen** [comment]
> Vår qa-adresse har spredd seg til media, så vi må rute qa til www, og lage ny qa-adresse for videre nettsideutvikling.

Det ser ut til at dette bare gjelder maskiner som er på Helse-Nord-nettet.
