### ISSUE TITLE
EPIC - URL ved valg av linechart, hvordan skal det løses - linechart

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2405]
Trengs mer diskusjon rundt struktur ved valg av graf, dagens løsning har url-kobling til graf. Ikke det samme i den nye charten. Samsvarer med #2408

**Comment by Stein-Kato** [comment]
@larstun Skal vi fortsatt ha id på åpen rad i url-en?

**Comment by larstun** [comment]
Krever mer diskusjon rundt denne
