### ISSUE TITLE
Lag registerspesifikke sider

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2408]
Stort sett samme komponenter som på alle-siden, men med enkelte modifikasjoner. Trenger ikke fagområde.

Vi har dette i dag.

![image](https://github.com/mong/mongts/assets/136346/4175aa9b-9ccb-49c9-be4b-a9b8e1d79f70)

**Comment by larstun** [comment]
Vurdere om registerspesfikke sider peker til kvalitetsregistre.no om kvalitetsregisteret,
for å vise registerets resultater går til registerets filtervalg for fagområde (https://test.skde.no/behandlingskvalitet/?indicator=reg-hjerneslag&disablemedicalfieldselection=true) pluss at valg av fagområde fjernes.

**Comment by larstun** [comment]
Legge til at default verdi for tøm filter ikke går tilbake til Alle fagområder men til valgene i URL (som holder seg til registerets fagområdevalg)

**Comment by Stein-Kato** [comment]
Vi skal ikke ha registerspesifikke sider
