### ISSUE TITLE
Utbedre indikatorliste for "Utvalge indikatorer" i sykehusprofil

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2448]
- [ ] Sortere på nevner (indikator med mest i nevner havner øverst)
- [ ] Sortere på dekningsgrad (indikator med best dekningsgrad havner øverst)
- [ ] Sortere på resultat (indikator med verst/best resultat havner øverst)
- [ ] Sette cut-off på maks 5 indikatorer per sykehus

Koblet mot #2429 
![Image](https://github.com/mong/mongts/assets/143407861/8fd24486-85e6-4cc8-a1a7-11b0463eab2a)

**Comment by Stein-Kato** [comment]
@larstun Er denne fortsatt aktuell?

**Comment by larstun** [comment]
Nei, denne utgår ettersom denne er kommet:

**Comment by Stein-Kato** [comment]
Ikke lenger relevant
