### ISSUE TITLE
Feilmelding etter oppgradering av biblioteker og next.js

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#2460]
Det har dukket opp en feilmelding når man kjører lokalt. Dette ser ut til å være relatert til en Next.JS-versjon og skal etter sigende allerede være fikset i et kanari-bygg av Next. 

Vurder om vi skal bruke annen versjon av Next.

![Image](https://github.com/mong/mongts/assets/9477329/46157596-013e-46f8-83ac-ef3c52b49a66)

**Comment by Stein-Kato** [comment]
Sjekk om denne er løst

**Comment by arnfinn** [comment]
Ganske sikker på at denne er borte
