### ISSUE TITLE
Sortere behandlingsenheter geografisk

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2468]
Må sortere RHFene geografisk fra Nord til Sør

1. Helse Nord
2. Helse Midt
3. Helse Vest 
4. Helse Sør-Øst

Koblet til: #2450 

![Image](https://github.com/mong/mongts/assets/143407861/9297e8a3-8549-43c0-9dcf-d075ebd672fc)

**Comment by arnfinn** [comment]
Fikset i https://github.com/mong/mongts/pull/2593
