### ISSUE TITLE
Linting ved commit sletter alle endringer

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#2500]
Når man kjører git commit, vil alle stagede endringer slettes hvis lintingen feiler.

Endringene er heldigvis stashet, slik at de kan fås tilbake, men funksjonaliteten bør skrus av.

![Image](https://github.com/mong/mongts/assets/9477329/a42be2f1-d38e-4194-aa4b-9647afcd473e)

**Comment by arnfinn** [comment]
Merkelig. Det har jeg ikke opplevd. Hva slags git-feil?

**Comment by arnfinn** [comment]
Jeg klarer ikke reprodusere dette. "Reverting to original state because of errors..." kjører helt fint hos meg.

**Comment by Stein-Kato** [comment]
Antar at det løste seg
