### ISSUE TITLE
Legge til tekst om datakvalitet i datakvalitetsfilteret

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2577]
@larstun Finn ut hva folk vil ha

**Comment by larstun** [comment]
Vi kan heller legge til en tekst som forteller noe om hva som skjer når man bruker switchen. Hvis tilbakmeldingen er massiv kritikk av datakvalitetsswitchen så får vi endre på det i neste versjon. Folket må vente.

![image](https://github.com/mong/mongts/assets/143407861/54bb4100-c16b-4166-b90b-1c0e00cbc67c)
