### ISSUE TITLE
Hente forsidebilde fra nettsider til HF/RHF

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2587]
- Hente alle bilder periodisk eller hente hvert enkelt bilde når man laster inn siden? 

![image](https://github.com/mong/mongts/assets/64078729/a8882d6d-916e-4ac9-861b-d4ec0d21be79)

**Comment by larstun** [comment]
URL til HF og RHF, bruk MUI icons til sykehusenhet istedenfor bilde fra RHF/HF sidene ( import LocalHospitalIcon from '@mui/icons-material/LocalHospital'; )

[Navn_HF_behandlingskvalitet.csv](https://github.com/mong/mongts/files/15483511/Navn_HF_behandlingskvalitet.csv)
[Navn_RHF_behandlingskvalitet.csv](https://github.com/mong/mongts/files/15483512/Navn_RHF_behandlingskvalitet.csv)

**Comment by larstun** [comment]
Kan løses med et automatisk/manuelt script som henter forsidebilde 1 x /uken eller 1 x/mnden som plukker ned forsidebilde og bruker i sykehusprofilen til sykehuset
