### ISSUE TITLE
Endre lenker til behandlingskvalitet på kvalitetsregistre.no

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2596]
Peker nå til f. eks. https://www.skde.no/kvalitetsregistre/hjerneslag/sykehus/. 
Skal peke til https://www.skde.no/behandlingskvalitet/?indicator=reg-hjerneslag. 

![Image](https://github.com/mong/mongts/assets/64078729/63d5e453-d002-4859-a9f0-f8f62bd2a9c2)

**Comment by larstun** [comment]
Gjennomført
