### ISSUE TITLE
application error: a clientside exception bug

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2597]
![Image](https://github.com/mong/mongts/assets/143407861/80b0a30a-5cbf-4b1d-bf3b-fc6148085a29)

**Comment by larstun** [comment]
Et eller annet som skjer når man skal vise de private i sykehusprofil på test.skde.no/sykehusprofil...

Og på www.skde.no/sykehusprofil som har den gamle Velg behandlingsenhet-menyen så kommer det behandlingsenheten fram mye raskere...

**Comment by Stein-Kato** [comment]
Virker som at #2757 løste dette.
