### ISSUE TITLE
Behold registeroverskrift, men skriv at data finnes på opptaksomr?

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2638]
MS leverer data på sykehus selv om de kun har data på opptaksområde. Dette for å dukke opp på forsiden av sykehusviser. Da kunne det stått at register har data på opptaksområde.

Det kunne også stått hvis register mangler data for gitt år men har data for året før?

**Comment by Stein-Kato** [comment]
Forslag: lag en tabell i databasen med en rad per register og kolonner for om de har data for sykehus og opptaksområder. Tabellen oppdateres ved aggregering eller datalevering.

**Comment by arnfinn** [comment]
> Forslag: lag en tabell i databasen med en rad per register og kolonner for om de har data for sykehus og opptaksområder. Tabellen oppdateres ved aggregering eller datalevering.

Finnes allerede, som  `vw_registry_contexts`.

![image](https://github.com/user-attachments/assets/2bdfc76a-d3d5-4698-b4a2-183ef600c85e)

**Comment by arnfinn** [comment]
@jo-inge-arnes

**Comment by Stein-Kato** [comment]
#3481 Må løses først

**Comment by larstun** [comment]
@Stein-Kato #3481 er løst, kan denne fikses?

**Comment by Stein-Kato** [comment]
> @Stein-Kato #3481 er løst, kan denne fikses?

Det kan den

**Comment by larstun** [comment]
https://github.com/mong/mongts/pull/3559#issuecomment-2548409539
