### ISSUE TITLE
Fjerne "Gynokologisk kreft" fra fagområde

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2694]
![image](https://github.com/mong/mongts/assets/143407861/1556d587-0b33-4b85-8368-5c941bc6c50b)
 

Fjerne gynekologisk kreft fra fagområde-filteret, registeret heter "Gynekologisk kreft" men de har fordelt fagområde i "Livmorhalskreft" og "Ovarialkreft" som de leverer data på...

**Comment by arnfinn** [comment]
Alle registrere som ligger under et fagområde i databasetabellen `registry_medfield` vises i oversikten, siden api-et looper over alle fagområder og kobler på alle registre som ligger under hvert fagområde i endepunktet `/info/medicalfields`. Ingen filtrering på om data finnes eller ikke. Spørringen ser slik ut:

```js
  db
    .select(
      "mf.name as shortName",
      "mf.full_name as name",
      "r.name as registers",
    )
    .from("registry_medfield as rmf")
    .leftJoin("medfield as mf", "rmf.medfield_id", "mf.id")
    .join("registry as r", "rmf.registry_id", "r.id")
    .orderBy("mf.id")
    .orderBy("r.id");
```

Fikset ved å fjerne `gynkreft` fra fagområdene `kreft` og `gyn`.
