### ISSUE TITLE
Brødsmulesti på mobil: kun siste side

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2720]
FNSP fjerner alle bortsett fra siste element, og legger på en pil

#2869 

![image](https://github.com/mong/mongts/assets/136346/3cf335be-1829-48df-bf29-f9f91b65eb46)

![image](https://github.com/mong/mongts/assets/136346/e0aa1f04-b771-487a-aa1d-f4d023ed8a9c)

**Comment by larstun** [comment]
@Uglemat kan du se på denne?
