### ISSUE TITLE
Krasj ved åpning to fagomr med likt register

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2752]
Reproduseres ved å åpne fagområde Kreft og så åpne fagområde Mage/tarm. Krasjer fordi ID er identisk når register går igjen.

![image](https://github.com/mong/mongts/assets/136346/5f3e540d-d59e-42c1-b8c0-1542041543be)

I produksjon får vi denne klassikern:

![image](https://github.com/mong/mongts/assets/136346/6b2d01b4-553e-4580-ba49-383c347f3212)

**Comment by larstun** [comment]
Skjer dette med flere register som er lagt inn i flere fagområder? Mitt forslag er selvsagt å fjerne register fra å ha flere fagområder og kun ligge i et fagområde

**Comment by arnfinn** [comment]
@larstun fix i #2754
