### ISSUE TITLE
Fikse fonter i linjediagram i sykehusprofil

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2791]

**Comment by larstun** [comment]
> @larstun Hva er kravspesifikasjonen her?
> 
> ![image](https://private-user-images.githubusercontent.com/64078729/354989577-5b42e5cc-f91e-4b33-9d58-a4c52b4056f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Mzk4NTgsIm5iZiI6MTcyMjgzOTU1OCwicGF0aCI6Ii82NDA3ODcyOS8zNTQ5ODk1NzctNWI0MmU1Y2MtZjkxZS00YjMzLTlkNTgtYTRjNTJiNDA1NmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA2MzIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NzIxYjkyZjE4ZmJmOTYxNGRhZjlmMWViYzQzNTI0OWFjM2IxNTgxMTVlZDAzZGQwOWU1ZWY4Zjk5ZjZkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qfLrCDgLQtXaEb_QWfyG8rFHQYbjJG1k42mAzhbCHTk)

![image](https://github.com/user-attachments/assets/1eb4a54c-dad2-4a5c-a489-e6f83c8b83eb)
Mulig å se til denne Figma skissen?
