### ISSUE TITLE
Footer: flytte HN-logo ned til høyre

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2870]
Ble flyttet opp til skde-logo i #2772 (@Uglemat). Stemmer ikke lenger med footer på skde.no.

På skde.no:
![image](https://github.com/user-attachments/assets/20c28d06-499e-403a-8431-49da1d9eb6aa)

Før #2772:
![image](https://github.com/user-attachments/assets/028e2097-0e3d-47fe-8223-c25bae379763)

Etter #2772:
![image](https://github.com/user-attachments/assets/d04f9fcd-b1dd-4a19-8d69-3fb001f55843)

**Comment by larstun** [comment]
Fjern HN logo fra footer...
