### ISSUE TITLE
Ikke vise register-header i sykehusprofil hvis ingen data/kvalitetsindikator

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2882]
Når det ikke finnes data for kvalitetsindikator under Siste års måloppnåelse så vises fortsatt registernavn som en overskrift.
- Sette regel på at det ikke skal vises registernavn i tabellen hvis det ikke finnes data

![Image](https://github.com/user-attachments/assets/44b9da96-debc-480f-9f55-9d441189887e)

**Comment by Stein-Kato** [comment]
API-et setter `var` til `null` hvis nevner er mindre enn `min_denominator`. 

I behandlingskvalitet vises ikke data hvis dekningsgrad er under 60 %. Skal vi filtrere ut disse indikatorene i sykehusprofilen og markere dem, eller ikke vise dem?
