### ISSUE TITLE
Siste års måloppnåelse - default verdi er "Lav" måloppnåelse

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2891]
Velg måloppnåelse skal ha default verdi på "Lav"...

![Image](https://github.com/user-attachments/assets/79b69342-0e69-4d1d-bf18-bef192b4c15d)

 og kan det brukes Mui-basic button med dropdown?

![Image](https://github.com/user-attachments/assets/9fbe58a2-ddfd-455f-a5da-029e2fe21fb0)

**Comment by Stein-Kato** [comment]
@larstun  Mui-button har ikke drowpdown, men de har select: https://mui.com/material-ui/react-select/

Funker den?
