### ISSUE TITLE
Bruke skeleton på behandlingskvalitet

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#2898]
For å unngå at man får footer rett i fleisen når man åpner siden.

Kan bruke https://mui.com/material-ui/react-skeleton/ for å gjøre det enkelt.

**Comment by larstun** [comment]
@Stein-Kato -  bruke på sykehusprofil også?

**Comment by Stein-Kato** [comment]
> [@Stein-Kato](https://github.com/Stein-Kato) - bruke på sykehusprofil også?

Har laget en issue på det: #3010
