### ISSUE TITLE
Infoboks oppdateres ikke når man trykker på tilknyttede enheter

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2900]
Bilde og lenke til nettside oppdateres ikke når man velger tilknyttet enhet. 

Må kanskje initialisere filtermenyen med `onFilterInitialized`. 

https://github.com/user-attachments/assets/3f3a09a8-ea3e-4902-8609-2f139d777228

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Kan du se på denne?

**Comment by jo-inge-arnes** [comment]
Får ikke gjenskapt denne på https://test.skde.no/sykehusprofil/

Kanskje rettet som følge av en annen fix?
