### ISSUE TITLE
Hoverbox over måloppnåelse med forklaring?

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2920]
Tilbakemelding om at det ønskes mer forklaringer på ulike ting i Sykehusprofil, burde det være en forklaring på hva måloppnåelse er for noe? En hoverbox med forklaring på hver av måloppnåelse...

Høy måloppnåelse: "Viser andel eller antall kvalitetsindikatorer som har oppnådd høy måloppnåelse i kvalitetsregisteret"
Middels måloppnåelse: "Viser andel eller antall kvalitetsindikatorer som har oppnådd middels måloppnåelse i kvalitetsregisteret"
Lav måloppnåelse: "Viser andel eller antall kvalitetsindikatorer som har oppnådd lav måloppnåelse i kvalitetsregisteret"

![Image](https://github.com/user-attachments/assets/ad822f36-af3e-47a9-b953-bccf1cbc1e8f)

**Comment by arnfinn** [comment]
[Aftenposten](https://www.aftenposten.no/amagasinet/i/mPQg0q/doedsbo-rydderne-rykker-inn-naar-hjem-blir-til-doedsbo):

![image](https://github.com/user-attachments/assets/b0c80757-8219-4f72-9591-3072117c1877)
