### ISSUE TITLE
Endre forklaringsstekst i "Siste års måloppnåelse" 

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2931]
Endre forklaringstekst til:
"Her er en interaktiv liste som gir oversikt over kvalitetsindikatorene ut fra siste års måloppnåelse for [full_name]. Du kan trykke på indikatorene for å se mer informasjon om indikatoren og følge oppgitt lenke til mer detaljert beskrivelse av indikatoren."

![Image](https://github.com/user-attachments/assets/56b2c5f5-eb29-49de-afeb-9194ef38f774)

**Comment by Stein-Kato** [comment]
Overstyrer denne #2919?
