### ISSUE TITLE
Fjerne overskrift [Registry_name] i tabellen for siste års måloppnåelse, og legge det inn i nedtrekksmeny for indikatorene.

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2933]
Flytt [registry_name] fra overskrift til inn i nedtrekksmeny per indikator.

![Image](https://github.com/user-attachments/assets/befcc6f1-94b1-4548-9d4b-6edaa56f4825)

**Comment by Stein-Kato** [comment]
Uenig, flytter overskrift til venstre og i bold
