### ISSUE TITLE
Styling på nedtrekksmeny for behandlingsenhet

### ISSUE THREAD

**Issue by larstun** [mong/mongts#2980]
Ligne mer på design fra Ramsalt
![image](https://github.com/user-attachments/assets/79f8aae0-2ae5-4b4f-ae59-6188e37307fd)

**Comment by Stein-Kato** [comment]
@larstun Hvordan skal den se ut når menyen er åpen?

**Comment by larstun** [comment]
![Image](https://github.com/user-attachments/assets/42cacfe0-4281-4781-89ca-5f2a08afdeda)


Noe sånt?
