### ISSUE TITLE
Trendpiler på målnivåtabell

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3012]
![Image](https://github.com/user-attachments/assets/b6bdbb1f-da9c-4ec3-b220-7cf899ea33c7)

**Comment by larstun** [comment]
- Er det året før som forteller om trenden peker opp eller ned? 
- Hvis det er bare 1 års data så må det være [TrendingFlat]
- Hvor mye tilsvarer at trenden peker opp eller ned? 1% eller 10%?
