### ISSUE TITLE
Fjern knapp for nedlasting

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3045]
![Image](https://github.com/user-attachments/assets/52c42244-fe77-4ae6-911c-921f6cb75671)

**Comment by larstun** [comment]
@Stein-Kato tilbakestille denne? Tydelig tilbakemelding på å beholde nedlastingsknapp fra ledelsen

**Comment by arnfinn** [comment]
KOMMER IKKE PÅ TALE!!!
