### ISSUE TITLE
Feil i tabellbredde og logo-plassering ved åpning av rad i mobil-visning for behandlingskvalitet

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#3067]
![Screenshot_20240905_070251_Chrome](https://github.com/user-attachments/assets/0b9d5c3c-82f2-4b52-bd19-40457bc12ee4)

**Comment by jo-inge-arnes** [comment]
Det flyter en logo over måloppnåelsene?

**Comment by arnfinn** [comment]
@Stein-Kato

**Comment by arnfinn** [comment]
@Stein-Kato Bug introdusert i  02abb4296c

**Comment by Stein-Kato** [comment]
> @Stein-Kato Bug introdusert i [02abb42](https://github.com/mong/mongts/commit/02abb4296ca1d8a192d1591757a08cd75ee25ad9)

Fikses i #3071
