### ISSUE TITLE
I meny står Nasjonalt alltid som valgt enhet

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#3092]
I menyen på sykehusprofil står alltid Nasjonalt valgt som enhet, selv om man har valgt en annen enhet.

Se f.eks. her:
![Skjermbilde 2024-09-09 kl  11 25 58](https://github.com/user-attachments/assets/e87ffdc6-22a5-4695-bad0-f5b8d5cfc560)

**Comment by Stein-Kato** [comment]
Fungerer i Chrome så lenge caching er slått på, men ikke i Firefox. 

I Firefox oppdateres ikke forsidebildet når man kommer inn via url. 

@jo-inge-arnes Kan du se på dette?

**Comment by jo-inge-arnes** [comment]
Får gjenskapt dette på Sykehusprofil-siden, også i Chrome, men ikke i Behandlingskvalitet. Skal debugge og se om jeg finner ut av det.

**Comment by jo-inge-arnes** [comment]
Har rettet. Noen bør teste i tillegg til meg.
