### ISSUE TITLE
Publisering av Sykehusprofil 🚀 

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3134]
Hva må huskes på for publisering av Sykehusprofil:

- [x] 1. oktober er dato for lansering 🚀 
- [ ] Sjekk bug-listen 🐛 
- [x] Siste testing av Sykehusprofil - dato?
- [x] Sette ruting til Sykehusprofil på skde.no 
- [x] Søkeoptimalisering Sykehusprofil - Google metadata?
- [ ] #3159
- [ ] Formidle Sykehusprofil til RHFene gjennom: Kvalitetsavdelinger? Kommunikasjonsavdelinger? i form av Nyhetsbrev?
- [ ] Formidle Sykehusprofil til FNSP? nyhetsartikkel?
- [ ] Formidle Sykehusprofil til Kvalitetsregistrene
- [ ]

**Comment by arnfinn** [comment]
@larstun, er ikke denne ferdig?
