### ISSUE TITLE
Tilknyttede behandlingsenheter vil ikke endre til valgt RHF/HF/Sykehus, bytter til Nasjonalt

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3136]
Forsøker å trykke på RHF/HF/Sykehus i Tilknyttede enheter, den hopper bare tilbake til Nasjonalt.

**Comment by Stein-Kato** [comment]
Fungerer i test nå

**Comment by Stein-Kato** [comment]
> Fungerer i test nå

Kun på pc, og ikke på sykehusnivå

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Kan dette ha kommet inn i #3123?

**Comment by Stein-Kato** [comment]
Fikset i #3182
