### ISSUE TITLE
Bedre fordeling av rader i "Kvalitetsindikator fordelt på fagområder" i mobilvisning

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3140]
Fordelingen lager svære rader og tar opp plass i mobilvisning![image](https://github.com/user-attachments/assets/865d0517-2bda-4407-8a53-cbf30eb8d90e)

**Comment by Stein-Kato** [comment]
Kan vi sette inn en beskjed om å snu telefonen for å se tabellen?
