### ISSUE TITLE
Logo kuttes i mobilvisning

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3142]
NSM logo kuttes i mobilvisning
![image](https://github.com/user-attachments/assets/4eb53232-4b6d-4d12-b75e-48d7072300c4)

**Comment by Stein-Kato** [comment]
Blir trangt i helseatlas og: 

![Image](https://github.com/user-attachments/assets/a7c659c5-bf39-4e18-961a-da7fd10715a3)
