### ISSUE TITLE
Move sentry auth token out of source code and replace with aws env

### ISSUE THREAD

**Issue by gabriofr** [mong/mongts#32]
@arnfinn : Glemte at dette ligger åpent så Sentry auth token havna her (glemte av at den er åpen): https://github.com/mong/mongts/blob/develop/sentry.properties 

Har slettet denne nå fra Sentry og ny må opprettes og legges inn som en .env var i github actions. 

Sentry tokens knyttes til bruker så egentlig best om dere oppretter en og legger denne inn selv (ser ikke ut som vi har tilgang til GA): https://sentry.io/settings/account/api/auth-tokens/

Jeg kan sørge for at appen leser token fra rett navn, bare send meg navnet på env var'en den blir lagt inn i.

**Comment by arnfinn** [comment]
holder det med disse rettighetene?

![image](https://user-images.githubusercontent.com/136346/122928096-d4ca8100-d369-11eb-9682-36a0870b8503.png)

**Comment by arnfinn** [comment]
Jeg har nå lagd en github secret: `SENTRY_TOKEN`

**Comment by arnfinn** [comment]
Not relevant anymore I guess
