### ISSUE TITLE
Mellomrom på mobilvisning Behandlingskvaliter

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3253]
Får et mellomrom på app-bar ved mobilvisning (iPhone 14 - Chrome)
![image](https://github.com/user-attachments/assets/5277a7b0-a667-4c4b-a337-85615adee5b5)

**Comment by larstun** [comment]
Vises sånn på registerspesifikk side, se apps.skde.no/behandlingskvalitet/noric

**Comment by arnfinn** [comment]
@larstun Er denne fremdeles der, eller ble den fikset i #3276? @jo-inge-arnes ?

**Comment by larstun** [comment]
Den er fikset
