### ISSUE TITLE
Filtermenyen oppdateres ikke når state i komponenten over endres

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3287]
I sykehusprofil endres ikke valgt enhet i filtermenyen når man velger ny enhet med knappene.

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Kan du se på denne?

**Comment by jo-inge-arnes** [comment]
Har ikke dette fungert fint før?

**Comment by jo-inge-arnes** [comment]
Men, ja. Klarer nok å finne ut hva det er og kan se på det i morgen, kanskje seinere i dag.
