### ISSUE TITLE
BUG! Test.skde.no/behandlingskvalitet kræsjer med skeleton når du velger behandlingsenheter

### ISSUE THREAD

**Issue by larstun** [mong/mongts#3298]
Når man velger flere behandlingsenheter så stoppes alt og bare viser skeleton og får serverside application error. 

![Image](https://github.com/user-attachments/assets/a0e053e7-3758-4912-bb5f-0d5f96cb7357)

**Comment by larstun** [comment]
Obs! @arnfinn avvent med å publisere til main, må reverte noen oppdateringer?

**Comment by Stein-Kato** [comment]
@larstun Får ikke reprodusert feilen. Har du en lenke?

**Comment by larstun** [comment]
Klarer ikke å reprodusere feilen, skjedde når jeg testet på hjemmenettverket. Det virker som siden jobber veldig når man bruker filtrene, det dukker også opp en scrollebar nederst.

**Comment by larstun** [comment]
Ukjent feil, mulig noe med adblocker og dårlig hjemmenett
