### ISSUE TITLE
Fjerne avhengigheten av globals.css

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#3313]
Blir for mye kluss med annen styling.

https://github.com/mong/mongts/blob/8c11f5d01d54105cb10c0fe6b7a25142307bbe4b/apps/skde/pages/_app.tsx#L1

**Comment by arnfinn** [comment]
Noe du har lyst til å se på @Uglemat ? Du er jo så glad i css

**Comment by Stein-Kato** [comment]
Påvirker hovedsaklig helseatlas. Bør erstattes med theme og stylede komponenter.

**Comment by larstun** [comment]
Påvirker også typografi i den gamle tabellen på Behandlingskvalitet

**Comment by Uglemat** [comment]
Lukket av  #3492
