### ISSUE TITLE
Få oversikt over domenenavn-registrarer og registere nytt domene

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#3463]
SKDE har mange domenenavn som er registrert hos diverse registrarer. Her er det en oppryddingsjobb å gjøre. Få oversikt over de ulike registrarene, vurder om de kan samles ett sted. Det skal antagelig også registreres et nytt domene. Gjør dette.

**Comment by jo-inge-arnes** [comment]
Sendte forespørsel til HN IKT for et par uker siden. Har bedt support om å purre på den. TTT

**Comment by jo-inge-arnes** [comment]
Prøver også å få oversikt over domener og registrarer for domener som ikke er .no

**Comment by jo-inge-arnes** [comment]
Har laget et excel-ark med domener. Har også bestilt domenenavn.

**Comment by larstun** [comment]
Hvem skal ha excel-arket? Ligger det tilgjengelig noen plass?

**Comment by jo-inge-arnes** [comment]
Ok, skal lukke.

Har ikke delt arket, men minn meg på å gjøre det

**Comment by jo-inge-arnes** [comment]
lukket
