### ISSUE TITLE
Sammentrykte kolonnetekster når skeleton vises

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#3478]
Når skjermenbredden ikke er veldig bred, ser det fortsatt ut til at teksten blir trykket sammen på høyresiden i behandlingskvalitet pga. skeleton:

![Image](https://github.com/user-attachments/assets/f8d83cf4-c87c-4e75-b533-1a8de0c98d15)

**Comment by Stein-Kato** [comment]
> Når skjermenbredden ikke er veldig bred, ser det fortsatt ut til at teksten blir trykket sammen på høyresiden i behandlingskvalitet pga. skeleton:
> 
> ![Image](https://github.com/user-attachments/assets/f8d83cf4-c87c-4e75-b533-1a8de0c98d15)

Klarer ikke å gjnskape feilen: 

https://github.com/user-attachments/assets/2b27bf62-a1f7-4953-a782-7390df7aa435

**Comment by arnfinn** [comment]
Fikset i #3467
