### ISSUE TITLE
Gi filtermenyen context

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3481]
Filtermenyen må kunne ta inn `context` slik at de registerspesifikke sidene skal kunne håndtere registre som kun har data på opptaksområde. Per nå settes `context` til "caregiver" til å begynne med uansett. 

For å teste: 
- Bruk lokal database. Slett alle data til MS-registeret med `context=caregiver` (bruk regexp på `ind_id` og let opp "ms_")
- Gå inn på den registerspesifikke siden til MS-registeret. Filtermenyen må kunne sette `context` til "resident" når man kommer inn på siden

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Kan du se på denne?

**Comment by arnfinn** [comment]
Denne sperrer for løsning på #513, #2638 og #3483.

**Comment by jo-inge-arnes** [comment]
Usikker på hva som menes her. Filtermenyen har allerede støtte for context. Det er knappene der man kan velge mellom behandlingsenheter og opptaksområde. Man kan også sette parameteret i URL-en, f. eks. med context=resident.

**Comment by jo-inge-arnes** [comment]
Tolker det sånn at komponenten skal ta inn et default-parameter for context. Det kan jeg ordne.

**Comment by jo-inge-arnes** [comment]
Man kan nå gi inn et valgfritt parameter _initialContext_, som enten kan være "resident" eller "caregiver".
