### ISSUE TITLE
Defekt appbar på mobil

### ISSUE THREAD

**Issue by jo-inge-arnes** [mong/mongts#3490]
Appbar-en i behandlingskvalitet har sluttet å være "sticky"/festet til toppen og forsvinner når man scroller nedover. Dette har nok oppstått den siste tiden, men gjelder også i apps.skde.no.

![Image](https://github.com/user-attachments/assets/56b082e2-5428-47f4-a868-bec279a305af)

**Comment by arnfinn** [comment]
Fikset i #3495
