### ISSUE TITLE
Gi kontekst til filtermeny på registerspesifikek sider

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3564]
![image](https://github.com/user-attachments/assets/adda4bdb-d85c-4c64-9109-85bcfb032c8c)

**Comment by jo-inge-arnes** [comment]
Fikk ikke dette helt til å fungere.

![image](https://github.com/user-attachments/assets/0c2e7cd7-4e98-4da5-af35-4ac29ad0daa9)

Hvis jeg setter år til 2020 for denne URL-en, så vil den endres til 2023. Helse Nord blir heller ikke valgt på siden, selv om valget blir stående i URL-en:
![image](https://github.com/user-attachments/assets/1ccee54e-15d6-4306-adcf-45416fda3548)
