### ISSUE TITLE
Lage RSS-feed for behandlingskvalitet

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#3614]
Oppskrift: 
- https://www.davegray.codes/posts/nextjs-how-to-build-an-rss-feed
- https://dev.to/promathieuthiry/creating-an-rss-feed-in-your-nextjs-project-20em

**Comment by jo-inge-arnes** [comment]
Hva er bakgunnen for denne?

Jeg har foreslått RSS et par ganger for å vise lister over Helseatlas på FNSP-siden men etter å ha diskutert med Roger, gikk vi bort fra den løsningen foreløpig. Grunnen var at innholdet i RSS-en som skal brukes på FNSP ikke blir til søkbart innhold der.

Men ser at denne saken gjelder Behandlingskvalitet. Hvordan er dette tenkt brukt?

**Comment by larstun** [comment]
> Bare et spørsmål: Hva er bakgunnen for denne?
> 
> Er klar over at jeg har foreslått RSS et par ganger for å vise lister over Helseatlas på FNSP-siden, men etter å ha diskutert med Roger, gikk vi bort fra den løsningen foreløpig. Grunnen er at innholdet i RSS-en som skal brukes på FNSP ikke blir til søkbart innhold der.
> 
> Men ser at denne saken gjelder Behandlingskvalitet. Hvordan er dette tenkt brukt?

Du må snakke med Roger, det er han som har bestilt det. Det er snakk om å gjøre Behandlingskvalitet og Sykehusprofil søkbart i FNSP søkemotoren ved å bruke RSS feed.

**Comment by jo-inge-arnes** [comment]
Innholdet I RSS-en bør vel være beskrivende titler, korte beskrivelser og lenker til registerspesifikke sider og indikatorene der Eller hva er innholdet i RSS-en?

Tenker også at RSS-en kan genereres ut fra data fra API-et og at man passer på å cache den.

**Comment by jo-inge-arnes** [comment]
Men nå henger jeg i alle fall med på hvilken sak det egentlig var snakk om her 😉

**Comment by larstun** [comment]
Må bare teste om det vil fungere, var et ønske fra Roger. Du må huske å ta ferie også 😃

**Comment by jo-inge-arnes** [comment]
God jul!

**Comment by larstun** [comment]
Får opp RSS-feeden på FNSP sidene men de interne søkemotorene fanger ikke opp søkeordene i tittel eller ingressen. Må undersøkes nærmere med FNSP. RSS-feeden fungerer ihvertfall, kan kanskje gjenbrukes på andre ting.
