### ISSUE TITLE
Erstatte netlifycms?

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#387]
Prosjektet er [ganske](https://www.github.com/netlify/netlify-cms/discussions/6503) dødt for tiden.

Alternativer:
- [strapi](https://github.com/strapi/strapi)
- [ghost](https://github.com/TryGhost/Ghost)
- [Sanity](https://www.sanity.io/)
- [optimizely](https://www.optimizely.com/no/)
- ...

**Comment by arnfinn** [comment]
NHN bruker Umbraco internt

**Comment by jo-inge-arnes** [comment]
Sjekket ut Umraco. Det er en ASP.NET (C#)-løsning, og det ser ut til at den hovedsaklig støtter Angular også. ASP.NET, C#, Angular, osv. er for så vidt ting jeg har god kjennskap til fra før, men tror det passer bedre med en CMS basert på Node og React  for vår del. F. eks. Strapi.

**Comment by jo-inge-arnes** [comment]
Ser at Strapi også har en plug-in for Algolia, så da kan man få indekseringsbiten for helseatlas-innhold integrert som del av CMS-en.

**Comment by jo-inge-arnes** [comment]
Lager en egen branch for å jobbe med overgangen fra Decap til Strapi.

**Comment by Stein-Kato** [comment]
Det er vedtatt å bruke Payload.
