### ISSUE TITLE
Ikke filtrer ut data hvis `type` er `null`

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#409]
Data ble fjernet her hvis `type` var lik `null` i indikatorbeskrivelsen.

https://github.com/mong/mong-api/blob/43d06ee52dd322004acfa1bf102767dc3c9fea1c/src/models/data/indicators.ts#L45-L47

**Comment by larstun** [comment]
Issue eller til informasjon? Burde vel snart ha en readme?

**Comment by larstun** [comment]
Tvinge brukere ved input om å ikke bruke "NULL" verdi på type #2395
