### ISSUE TITLE
Indikator vises ikke hvis nasjonale tall mangler

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#511]
Burde dukke opp i tabellen hvis det finnes data på annet nivå.

~~Har ett par indikatorer som ikke har data på nasjonalt nivå, og hvis de er de eneste indikatorene et år under en fane dukker de aldri opp. Selv om man velger HF som finnes i dataene.~~ (sannsynligvis en annen grunn til dette)

**Comment by larstun** [comment]
Løst?
