### ISSUE TITLE
Bedre søkefunksjon under "Søk etter behandlingsenheter"

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#516]
Søk her vil også gi treff på langt navn.
![image](https://user-images.githubusercontent.com/136346/146002539-41cfc8cd-f1d4-4dfe-a65c-ce383d61e326.png)

Hvis man f.eks søker på UNN vil Tromsø, Harstad og Narvik komme opp.

EDIT: Ikke relevant hvis vi fjerner søk-funksjon

**Comment by larstun** [comment]
Ny søkeboks etablert i filteret
