### ISSUE TITLE
Tydeligere "velg behandler" funksjon

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#519]
"Vis alle"-knappen er for noen vanskelig å finne. Den burde fremheves mer (flyttes til venstre for søkefelt?) og kanskje hete noe som "Finn ditt sykehus" eller "Velg sykehus".

Ser slik ut i dag:
![image](https://user-images.githubusercontent.com/136346/131101159-c6bcc8bc-2649-4b6f-9ea8-4deabaefd699.png)

**Comment by Stein-Kato** [comment]
Løses med ny side
