### ISSUE TITLE
Knapp ved siden av registernavn som går til registersider

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#522]
- [x] Legge inn ett par kolonner til `registry` i databasen:
  - `url` der man legger inn registeret sin nettside.
  - `description` Kort tekst om registeret som kan vises på registersiden.
- [x] Legge disse to kolonnene inn i `view`.
- [ ] Hente dette inn i app og legge på.
- [ ] Fiks at knapp legger seg over tabell-header. 

@areedv tar du de to første?

Teksten og url skal dukke opp i banneret der det står navn på register.

![image](https://user-images.githubusercontent.com/136346/121027515-4ec60c00-c7a7-11eb-8b9c-01330e77540a.png)

**Comment by Stein-Kato** [comment]
TODO: Legge til knapp i header til indikatortabell som linker til registerside


![Image](https://github.com/mong/mongts/assets/64078729/4f765284-0f3d-4575-b8c2-7e820fd7ad20)

**Comment by Stein-Kato** [comment]
> TODO: Legge til knapp i header til indikatortabell som linker til registerside
> 
> ![Image](https://private-user-images.githubusercontent.com/64078729/335499473-4f765284-0f3d-4575-b8c2-7e820fd7ad20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAwODAsIm5iZiI6MTcxODY5OTc4MCwicGF0aCI6Ii82NDA3ODcyOS8zMzU0OTk0NzMtNGY3NjUyODQtMGYzZC00NTc1LWI4YzItN2U4MjBmZDdhZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTA5NjNkNDQ5MzA0MTY1MDdlODk5MjU3NGU5NGYxNzlkM2U4ODk3Y2YzOWEzOTAxMzBlNjJhMmEzMzgyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMF91tduGGe0S3BW-LLjRhDE2UNqEYB-Ut2NLUTgj8Y)

Dvs. registerspesifikke sider på behandlingskvalitet

**Comment by Stein-Kato** [comment]
@larstun @arnfinn  Ble vi enige om at knappen burde være på registerspesifikk side?

**Comment by larstun** [comment]
> [@larstun](https://github.com/larstun) [@arnfinn](https://github.com/arnfinn) Ble vi enige om at knappen burde være på registerspesifikk side?

Ja, legges til ny epic for registerspesifikke sider
