### ISSUE TITLE
verify: komme klart frem at det ikke er produksjonsdata som presenteres

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#524]
- Bytte ut banner med noe rødlig, inkludert fornuftig tekst.
- ~~Vise alle tall, selv små N?~~

Forslag til hvordan dette kan løses: Definere en miljøvariabel `VERIFY` som `TRUE` før app bygges.

**Comment by larstun** [comment]
Forslag: OBS! Dette er en verifiseringside for testdata, hvis du ønsker å se offisielle tall må du gå til apps.skde.no/behandlingskvalitet 

RØD STOR BOKS I HØYRE SIDE (FARE FARGE) Color.palette (Warning)
