### ISSUE TITLE
Keep percentage and color dot on same line

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#530]
See 100% here:

![image](https://user-images.githubusercontent.com/136346/96883389-a9ad2c00-1480-11eb-9926-2db37253be9e.png)

**Comment by larstun** [comment]
Gammel issue? Løst? @arnfinn

**Comment by arnfinn** [comment]
> Gammel issue? Løst? @arnfinn 

Ser nesten sånn ut

![image](https://github.com/mong/mongts/assets/136346/cec1abd3-d9df-4e25-8a0c-92f16eccc5d1)
