### ISSUE TITLE
 breadcrumbs link not working

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#6]
Ønsker å kunne trykke på *SKDE* i stien under, men dette er ikke en aktiv lenke.

![image](https://user-images.githubusercontent.com/136346/119461436-fe2ec780-bd3f-11eb-9d6a-bdabc42fe1d6.png)

https://d13kv0v5vl0wju.cloudfront.net/news/kvalitetsatlas

**Comment by gabriofr** [comment]
Heia,
https://github.com/mong/mongts/blob/1be55ed0323dba12622755eafe218d4af8db457d/components/layout.tsx#L55

Endre linja over til : 
```javascript
         <li><Link href="https://skde.no"><a>SKDE</a></Link></li>
```
