### ISSUE TITLE
Feil hvis yarn.lock bygges på nytt

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#840]
Dette ble gjort i `dependency_update` branch, som gjør at den feiler. Hele /kvalitetsregistre/alle/sykehus er nede:

![image](https://user-images.githubusercontent.com/136346/220928710-8155512b-dc47-4301-8c46-06a1cf30da2f.png)

## Reprodusere

```bash
rm yarn.lock
yarn install
export NEXT_PUBLIC_API_HOST="https://prod-mong-api.skde.org"
yarn dev
```

Gå så inn på http://localhost:3000/kvalitetsregistre/alle/sykehus/

**Comment by yte0** [comment]
https://www.github.com/amannn/next-query-params/issues/11#issuecomment-1102153817

**Comment by arnfinn** [comment]
Fikset i 46460a1529
